### ISSUE TITLE
Problem building xenon-common with maven wrapper 

### ISSUE THREAD

**Issue by sdrori** [vmware/xenon#11]
Started with a fresh install of Ubuntu Linux (14.04.5 LTS), installed Java 8 ((build 1.8.0_111-b14)) and git (just to download the xenon source code).

Using the maven wrapper to build the project, but tests fail in the middle of xenon-common with the message:
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3:exec (go-get) on project xenon-common: Command execution failed. Cannot run program "make" (in directory "/home/ubuntu/projects/xenon/xenon-common/src/main/go"): error=2, No such file or directory -> [Help 1]

Indeed, the make file in xenon-common/src/go is named 'Makefile' - though in creating a copy with that name and the same permissions yields this error.

**Comment by georgechrysanthakopoulos** [comment]
the xenon client directory uses Go Language tools, and requires go install.
you can skip the go client and any Go related code by using maven with the -DskipGO flag

mvn test -DskipGO

**Comment by georgechrysanthakopoulos** [comment]
btw we will be removing the go dependencies from the xenon repo, and moving it to xenon-utils, which is a new, peer, git hub repo for xenon related utilities and third party tools

**Comment by georgechrysanthakopoulos** [comment]
go tool chain is removed, part of xenon-utils top level (peer) repo now
