### ISSUE TITLE
remove use of String.replace() in code, replace with implementation similar to StringUtils.replace in apache commons (or Java9)

### ISSUE THREAD

**Issue by georgechrysanthakopoulos** [vmware/xenon#19]
recently discovered (from an article) that string.replace() uses regular expressions under the covers which is incredibly wasteful for short strings (anything less than a few K which is 99.999 of all xenon strings).

instead, java 9 has fixed this, but in our code we can add a Utils.replace(string, string) implementation using the java9/apache commons approach.

i searched and we dont use string.replace() widely but we do use it in some critical paths.

fyi @ttddyy @toliaqat 

feel free to close this and open a Tracker issue instead

**Comment by ttddyy** [comment]
Thanks @georgechrysanthakopoulos 

I just created a tracker item and added more details.
https://www.pivotaltracker.com/story/show/151964775

This is the original working item for openjdk for this issue:
https://bugs.openjdk.java.net/browse/JDK-8058779
