### ISSUE TITLE
Regression due to ODL changes: warning on PATCHs to subscriptions

### ISSUE THREAD

**Issue by georgechrysanthakopoulos** [vmware/xenon#20]
After recent ODL changes i start noticing the following messages (they happen every time my tasks are created through the xenon task factory, which subscribes to each child it creates. this is all default behavior)

ODL conflict: retrying PATCH (1537 null) on /core/callbacks/mgmt-shell-command-tasks-b1295a413582890555b731cc63e10-b1295a413582890555b731cc645e0]

they did not use to happen. its almost like we are trying to ressurect in memory only tasks, which have, by design, stopped/expired.

i dont have any other details but i suggest you look for the message in Jenkins logs, during our tests and see if you see anything ODL related on "/callback" links

@asafka @ttddyy

**Comment by asafka** [comment]
Hi George, I'll take a look.
Asaf

**Comment by asafka** [comment]
I believe this now addressed with https://github.com/vmware/xenon/commit/6b1e3692553a6a1cb845a029b99b9aaf6d8d6493.

**Comment by georgechrysanthakopoulos** [comment]
thanks!
