### ISSUE TITLE
vra 7.3 stuck on spinning wheel

### ISSUE THREAD

**Issue by steveschofield** [vmware/xenon#24]
Not sure this is the right location, asking :)   Within the Admiral interface in vRA 7.3, it recently stopped working and stuck on a spinning wheel.   VCH hosts aren't being shown.  I restarted the xenon service within VAMI and reported the cluster (we have two nodes).  Any ideas?

**Comment by toliaqat** [comment]
Hi Steve,

We use the pivotal tracker for tracker bugs and slack for the chat. Can you file a bug on pivotal for this? 
In your bug report at Pivotal, Can you add the following information?
1. Xenon version
2. Repro steps

Thanks,
Touseef

**Comment by sumamohan** [comment]
Even i have the same issue with vRA 7.2. Please help as its a critical environment at present. I've a demo coming up..
[xenonHost.0.log](https://github.com/vmware/xenon/files/1419282/xenonHost.0.log)
[xenon_service.log](https://github.com/vmware/xenon/files/1419283/xenon_service.log)

**Comment by toliaqat** [comment]
Please file a bug in pivotal tracker or send a question in slack channel. Closing this issue.
