### ISSUE TITLE
ReflectionUtils.setOrUpdatePropertyValue doesn't replace the Set elements

### ISSUE THREAD

**Issue by dido2k** [vmware/xenon#8]
In ReflectionUtils.setOrUpdatePropertyValue

This line:
existingCollection.addAll((Collection<Object>) value);

will NOT replace the set elements. The opposite is described in the javadoc:
"and the new values replace existing entries for a set"

Kind Regards,
Diyan.

**Comment by georgechrysanthakopoulos** [comment]
Thank you for the item, but please use the public Pivotal Tracker for xenon:
https://www.pivotaltracker.com/n/projects/1471320
